package com.co.biu.ecommerce.enums;

public enum TipoExcepcionInventario {
	PRODUCTO_INVALIDO, ELIMINAR_PRODUCTO_INVENTARIO_VACIO, REPORTE_VACIO, USUARIO_SIN_LOGEAR,
	ELIMINAR_PRODUCTO_INEXISTENTE, CANTIDAD_INVALIDA
}
